name: immutable_fsm
description: An immutable state machine that supports transient states, integrates with various 
  state and data management frameworks, and is ideal for UI applications.
version: 1.1.0
repository: https://github.com/zysoft/immutable_fsm

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  fast_immutable_collections: ^11.0.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
